### ISSUE TITLE
NullPointerException in Dynamic Project Working Set wizard

### ISSUE THREAD

**Issue by frankbenoit** [rherrmann/eclipse-extras#53]
I create a filter, the preview shows the matching projects, the finish button is enabled.
But pressing the "Finish" button does nothing.

Eclipse IDE for Eclipse Committers
Version: Oxygen Release Milestone 4 (4.7.0 M4)
Build id: 20161215-0740
OS: Windows 7, v.6.1, x86_64 / win32

Event log has:
```
eclipse.buildId=4.7.0.I20161208-0830
java.version=1.8.0_92
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product -product org.eclipse.epp.package.committers.product -data file:/D:/Project/Castle5/2_Castle5_Dev/2_EclipseWorkspaceJavaOxygen/ -product org.eclipse.epp.package.committers.product

This is a continuation of log file D:\Project\Castle5\2_Castle5_Dev\2_EclipseWorkspaceJavaOxygen\.metadata\.bak_0.log
Created Time: 2017-01-11 11:16:31.861

org.eclipse.ui
Error
Wed Jan 11 11:28:50 CET 2017
Unhandled event loop exception

java.lang.NullPointerException
	at com.codeaffine.extras.workingset.internal.DynamicWorkingSetPage.finish(DynamicWorkingSetPage.java:81)
	at org.eclipse.ui.internal.dialogs.WorkingSetNewWizard.performFinish(WorkingSetNewWizard.java:138)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:790)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:423)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:622)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4431)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4241)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.ui.internal.dialogs.AbstractWorkingSetDialog.createWorkingSet(AbstractWorkingSetDialog.java:251)
	at org.eclipse.ui.internal.dialogs.AbstractWorkingSetDialog$1.widgetSelected(AbstractWorkingSetDialog.java:123)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4431)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4241)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.ui.internal.dialogs.AbstractWorkingSetDialog.open(AbstractWorkingSetDialog.java:314)
	at org.eclipse.ui.internal.actions.SelectWorkingSetAction.run(SelectWorkingSetAction.java:72)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4431)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4241)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1133)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:698)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

**Comment by rherrmann** [comment]
Sorry to read that you are having trouble using working sets. However, I am having difficulties to reproduce the issue on my system (exact same Eclipse milestone build and Win 7)

As with most NullPointExceptions, the reference shouldn't be null at that point ;-) In this case it is the working set object that is about to be created but is supplied from _outside_, i.e. by Eclispe platform code. Understanding when this reference is null would help here.

Can you explain how/from where the wizard is invoked?

To ensure that you are using the most recent version of Extras for Eclipse, could you please also send the version number?

**Comment by frankbenoit** [comment]
It is a newly created installation, this is the first working set. Perhaps this is the reason?

**Comment by frankbenoit** [comment]
Package Explorer -> menu -> Select working set ...
"Window Working Sets", List is empty.
New ...
Dynamic Project Working Set
As pattern i give "name.*"

**Comment by rherrmann** [comment]
Gotcha! Thank you for the hint. I will publish a fix as soon as possible.

**Comment by rherrmann** [comment]
A new version should be available in a few minutes from here: https://rherrmann.github.io/eclipse-extras/repository/

Please feel free to re-open this issue if you still experience the problem.

**Comment by frankbenoit** [comment]
thanks, works now
